name: Customer Churn CI/CD

on:
  push:
    branches:
      - main

jobs:

  train-and-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install packages
      run: |
        pip install -r requirements.txt
        pip install -r requirements-train.txt

    - name: Train model
      run: |
        cd src
        python train.py

    - name: Run tests
      run: |
        pytest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}

        script: |

          cd churn-prediction-api

          git pull

          sudo docker stop $(sudo docker ps -q) || true
          sudo docker rm $(sudo docker ps -aq) || true

          sudo docker build -t churn-api .

          sudo docker run -d \
          --restart always \
          -e API_KEY=${{ secrets.API_KEY }} \
          -p 8001:8001 \
          churn-api