name: Customer Churn CI/CD

on:
  push:
    branches:
      - main

jobs:

  train-and-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install packages
      run: |
        pip install -r requirements.txt

    - name: Train model
      run: |
        cd src
        python train.py

    - name: Build Docker image
      run: |
        docker build -t churn-api .